dataset:
  name: 'UCR'
  in_channels: 1
  data_scaling: True
  batch_size: 128
  num_workers: 0

exp_params:
  LR: 0.001  # learning rate

trainer_params:
  # gpus:
  #   - 0
  # max_epochs: 1000
  devices:
    - 0
  max_steps: 20000 #5000
  check_val_every_n_epoch: 5


